tickets/urls.py
from django.urls import path
from .views import home, ticket_view, ticket_close, ticket_delete, ticket_block, ticket_unblock

app_name = 'tickets'

urlpatterns = [
    path('', home, name='Tickets'),
    path('id/<int:ticket_id>/', ticket_view, name='Tickets'),
    path('id/<int:ticket_id>/close/', ticket_close, name='Ticket'),
    path('id/<int:ticket_id>/delete/', ticket_delete, name='Ticket'),
    path('id/<int:ticket_id>/block/', ticket_block, name='Ticket'),
    path('id/<int:ticket_id>/unblock/', ticket_unblock, name='Ticket'),
]

tickets/models.py
from django.db import models
from Main.models import User
from django.conf import settings


# Create your models here.

class Ticket(models.Model):
    title = models.CharField(max_length=32)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='User')
    handled_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, related_name='Admin', null=True)
    problem = models.TextField(max_length=255)
    solved = models.BooleanField(default=False)
    blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.title + ' [' + str(self.user) + ']'


class Response(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=255)

    def __str__(self):
        return str(self.ticket.title) + ' [' + str(self.user) + '] ' + str(self.id)

tickets/forms.py
from django import forms


class ValidateResponse(forms.Form):
    text = forms.CharField(error_messages={'required': 'Reply can not be empty'})

    def clean(self):
        text = str(self.cleaned_data.get('text'))
        if text is None:
            raise forms.ValidationError('Reply can not be empty')
        return True


class ValidateTicket(forms.Form):
    title = forms.CharField(error_messages={'required': 'Title can not be empty'})
    text = forms.CharField(error_messages={'required': 'Description can not be empty'})

    def clean(self):
        title = str(self.cleaned_data.get('title'))
        text = str(self.cleaned_data.get('text'))
        if text is None or title is None:
            raise forms.ValidationError('Reply or title can not be empty')
        return True

tickets/views.py
from django.shortcuts import render, redirect
from .models import Ticket, Response
from .forms import ValidateResponse, ValidateTicket
from django.http import HttpResponseNotFound

SERVER_NAME = 'Example server'


# Create your views here.
def home(request):
    if not request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = ValidateTicket(request.POST)
        if form.is_valid():
            ticket = Ticket.objects.create(user=request.user, title=request.POST['title'], problem=request.POST['text'])
            return redirect('/tickets/id/' + str(ticket.id))
    tickets = Ticket.objects.filter(user=request.user)
    if not request.user.is_staff:
        context = {
            'ticket_quantity': tickets.count(),
            'tickets': tickets,
            'user': request.user,
            'SERVER_NAME': SERVER_NAME,
            'Title': 'Tickets',
        }
    else:
        user_tickets = Ticket.objects.all()
        context = {
            'ticket_quantity': tickets.count(),
            'tickets': tickets,
            'user_tickets': user_tickets,
            'user': request.user,
            'SERVER_NAME': SERVER_NAME,
            'Title': 'Tickets',
        }
    return render(request, 'Tickets/tickets.html', context)


def ticket_close(request, ticket_id):
    if not request.user.is_authenticated:
        return redirect('/')
    tickets = Ticket.objects.filter(id=ticket_id)
    if tickets.count() != 0:
        if tickets.first().user == request.user or request.user.is_staff:
            tickets = Ticket.objects.filter(id=ticket_id).first()
            tickets.solved = True
            tickets.save()
            if request.user.is_staff:
                Response.objects.create(user=request.user, text='<strong>Closed by administrator. If you have any'
                                                                ' question feel free to reply again</strong>',
                                        ticket=tickets)
            else:
                Response.objects.create(user=request.user, text='<strong>Closed by user</strong>', ticket=tickets)
            return redirect('/tickets/id/' + str(ticket_id))
        else:
            return redirect('/tickets')
    else:
        return


def ticket_unblock(request, ticket_id):
    if not request.user.is_authenticated:
        return redirect('/')
    tickets = Ticket.objects.filter(id=ticket_id)
    if tickets.count() != 0:
        if request.user.is_staff:
            tickets = Ticket.objects.filter(id=ticket_id).first()
            tickets.blocked = False
            tickets.save()
            return redirect('/tickets/id/' + str(ticket_id))
        else:
            return redirect('/tickets')
    else:
        return render(request, 'Main/templates/404.html', status=404)


def ticket_block(request, ticket_id):
    if not request.user.is_authenticated:
        return redirect('/')
    tickets = Ticket.objects.filter(id=ticket_id)
    if tickets.count() != 0:
        if request.user.is_staff:
            tickets = Ticket.objects.filter(id=ticket_id).first()
            tickets.blocked = True
            tickets.save()
            if request.user.is_staff:
                Response.objects.create(user=request.user, text='<strong>Administrator blocked possibility to '
                                                                'answer for this ticket. Keep on mind opening more '
                                                                'ticket could affect ban</strong>',
                                        ticket=tickets)
            return redirect('/tickets/id/' + str(ticket_id))
        else:
            return redirect('/tickets')
    else:
        return render(request, 'Main/templates/404.html', status=404)


def ticket_delete(request, ticket_id):
    if not request.user.is_authenticated:
        return redirect('/')
    tickets = Ticket.objects.filter(id=ticket_id)
    if tickets.count() != 0:
        if request.user.is_staff:
            tickets = Ticket.objects.filter(id=ticket_id).first()
            tickets.delete()
            return redirect('/tickets')
        else:
            return redirect('/tickets')
    else:
        return render(request, 'Main/templates/404.html', status=404)


def ticket_view(request, ticket_id):
    if not request.user.is_authenticated:
        return redirect('/')
    tickets = Ticket.objects.filter(id=ticket_id)
    if tickets.count() != 0:
        if tickets.first().user == request.user or request.user.is_staff:
            reply = Response.objects.filter(ticket=tickets.first())
            context = {
                'replies': reply,
                'ticket': tickets.first(),
                'user': request.user,
                'SERVER_NAME': SERVER_NAME,
                'Title': 'Ticket',
            }
            if tickets.first().blocked is True:
                context = {
                    'replies': reply,
                    'ticket': tickets.first(),
                    'user': request.user,
                    'SERVER_NAME': SERVER_NAME,
                    'Title': 'Ticket',
                    'Blocked': True,
                }
                return render(request, 'Tickets/ticket.html', context)
            if request.method == 'POST':
                forms = ValidateResponse(request.POST)
                if forms.is_valid():
                    Response.objects.create(user=request.user, ticket=tickets.first(), text=request.POST['text'])
                    tickets = Ticket.objects.filter(id=ticket_id).first()
                    if not request.user.is_staff:
                        tickets.solved = False
                        tickets.save()
                    else:
                        tickets.handled_by = request.user
                        tickets.save()
                    return redirect('/tickets/id/' + str(ticket_id))
            return render(request, 'Tickets/ticket.html', context)
        else:
            return redirect('/tickets')
    else:
        return render(request, 'Main/templates/404.html', status=404)

tickets/templates/tickets/admin_modal.html
<!-- Modal -->
<div class="modal fade" id="admin_panel" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Admin panel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <a href="/tickets/id/{{ ticket.id }}/close"><button type="button" class="btn btn-warning">Close ticket</button></a>
          <a href="/tickets/id/{{ ticket.id }}/delete"><button type="button" class="btn btn-danger">Delete ticket</button></a>
          <a href="/tickets/id/{{ ticket.id }}/block"><button type="button" class="btn btn-info">Block ticket</button></a>
          <a href="/tickets/id/{{ ticket.id }}/unblock"><button type="button" class="btn btn-success">Unlock ticket</button></a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

tickets/templates/tickets/ticket.html
{% extends 'Main/templates/root.html' %}
{% block content %}

    <!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Ticket ID {{ ticket.id }}</h1>

            <hr class="hr-light">

            <p>
              <strong>{{ ticket.title }}</strong>
            </p>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
    <!--Main layout-->
    <main>
        <div class="container padding-bottom-3x mb-2">
            <div class="row">
                <div class="col-lg-4">
                <br>
                {% include 'tickets/user_sidebar.html' %}
                <div class="wizard">
                    <nav class="list-group list-group-flush">
                        <a class="list-group-item active" href="">
                            <div class="d-flex justify-content-between align-items-center">
                                <div><i class="fa fa-tag mr-1 text-muted"></i>
                                    <div class="d-inline-block font-weight-medium text-uppercase">Inspecting Ticket</div>
                                </div>
                            </div>
                        </a>
                         <a class="list-group-item" href="/tickets/"><i class="fa fa-ticket-alt text-muted"></i>Ticket list</a>
                        <a class="list-group-item" href="#"><i class="fa fa-user text-muted"></i>Profile</a>
                        {% if ticket.solved == False %}
                            <a class="list-group-item badge-danger" href="/tickets/id/{{ ticket.id }}/close"><i class="fa fa-window-close text-muted"></i>Close ticket</a>
                        {%  endif %}
                        {% if user.is_superuser %}
                            {% include 'tickets/admin_modal.html' %}
                            <a class="list-group-item" data-toggle="modal" data-target="#admin_panel"><i class="fa fa-user-shield text-muted"></i>Admin panel</a>
                        {% endif %}
                    </nav>
                </div>
            </div>
                <div class="col-lg-8">
                    <div class="padding-top-2x mt-2 hidden-lg-up"></div>
                    <div class="table-responsive margin-bottom-2x">
                        <table class="table margin-bottom-none">
                            <thead>
                                <tr>
                                    <th>Ticket ID</th>
                                    <th>Title</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                    <th>Handled by</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.id }}</a></td>
                                    <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.title }}</a></td>
                                    <td>{{ ticket.created }}</td>
                                    {% if ticket.blocked == True %}
                                        <td><span class="badge badge-danger m-0">Blocked</span></td>
                                    {% elif ticket.solved == True %}
                                        <td><span class="badge badge-warning m-0">Closed</span></td>
                                        {% else %}
                                        <td><span class="badge badge-primary m-0">Open</span></td>
                                    {% endif %}
                                    <td><span>{{ ticket.handled_by.nickname }}</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="comment">
                            <div class="comment-author-ava"><img src="https://mc-heads.net/head/{{ ticket.user.nickname }}" alt="Avatar"></div>
                            <div class="comment-body">
                                <p class="comment-text">{{ ticket.problem }}</p>
                                <div class="comment-footer"><span class="comment-meta"> {{ ticket.user.nickname }}, {{ ticket.created|date:"d M Y" }} {{ ticket.created|time:"H:i" }}</span></div>
                            </div>
                    </div>
                    {% for reply in replies %}
                         <div class="comment">
                            <div class="comment-author-ava"><img src="https://mc-heads.net/head/{{ reply.user.nickname }}" alt="Avatar"></div>
                            <div class="comment-body">
                                <p class="comment-text">{{ reply.text|safe }}</p>
                                <div class="comment-footer"><span class="comment-meta">{% if reply.user.is_superuser %}<p class="badge badge-danger">Admin</p> {% endif %} {{ reply.user.nickname }}, {{ reply.time|date:"d M Y" }} {{ reply.time|time:"H:i" }}</span></div>
                            </div>
                        </div>
                    {% endfor %}
                    <form method="post"> {% csrf_token %}
                        <div class="form-group">
                            {% if Blocked is not True %}
                                <h5 class="mb-30 padding-top-1x">Leave Message</h5>
                                <div class="text-right">
                                    <textarea class="form-control form-control-rounded" id="id_text" name="text" rows="8" placeholder="Write your text here..." required=""></textarea>
                                    <button class="btn btn-outline-primary" type="submit">Submit Message</button>
                                </div>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <!--Main layout-->

  <!-- Full Page Intro -->

{% endblock %}

tickets/templates/tickets/ticket_modal.html
<!-- Modal -->
<div class="modal fade" id="new_ticket" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New ticket</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                <form method="post"> {% csrf_token %}
                  <label for="title" class="sr-only">Username</label>
                  <input type="text" id="id_username" class="form-control" name="title" placeholder="Title of ticket" required autofocus><br/>
                  <label for="text" class="sr-only">Password</label>
                   <textarea class="form-control form-control-rounded" id="id_text" name="text" rows="8" placeholder="Write your text here..." required=""></textarea>
                    <br>
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />
                </form>
      </div>
    </div>
  </div>
</div>

tickets/templates/tickets/tickets.html
{% extends 'Main/templates/root.html' %}
{% block content %}
    {% include 'tickets/ticket_modal.html' %}
    <!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Ticket</h1>

            <hr class="hr-light">

            <p>
              <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Duis ut nisi tempus velit sollicitudin fermentum sed id quam. Nam eu sem vitae leo pretium iaculis et eget tortor. Sed molestie lorem id dolor euismod porta.</strong>
            </p>

            <a target="_blank" data-toggle="modal" data-target="#new_ticket" class="btn btn-indigo btn-lg">Submit new ticket
              <i class="fas fa-ticket-alt ml-2"></i>
            </a>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
    <!--Main layout-->
    <main>
<div class="container mb-4 main-container">
    <div class="row">
        <div class="col-lg-4 pb-5">
            <!-- Account Sidebar-->
            {% include 'tickets/user_sidebar.html' %}
            <div class="wizard">
                <nav class="list-group list-group-flush">
                    <a class="list-group-item active">
                        <div class="d-flex justify-content-between align-items-center">
                            <div><i class="fa fa-tag mr-1 text-muted"></i>
                                <div class="d-inline-block font-weight-medium text-uppercase">Ticket list</div>
                            </div><span class="badge badge-secondary">{{ ticket_quantity }}</span>
                        </div>
                    </a>
                    <a class="list-group-item" href="#"><i class="fa fa-user text-muted"></i>Profile</a>
                </nav>
            </div>
        </div>
        <!-- Orders Table-->
        <div class="col-lg-8 pb-5">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Ticket ID</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Handled by</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ticket in tickets %}
                        <tr>
                            <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.id }}</a></td>
                            <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.title }}</a></td>
                            <td>{{ ticket.created }}</td>
                            {% if ticket.blocked == True %}
                                <td><span class="badge badge-danger m-0">Blocked</span></td>
                            {% elif ticket.solved == True %}
                                <td><span class="badge badge-warning m-0">Closed</span></td>
                                {% else %}
                                <td><span class="badge badge-primary m-0">Open</span></td>
                            {% endif %}
                            <td><span>{{ ticket.handled_by }}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% if user.is_superuser == True %}
            <br><br>
                <h2>User tickets</h2>
                <table class="table table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Ticket ID</th>
                            <th>User</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Handled by</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ticket in user_tickets %}
                        <tr>
                            <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.id }}</a></td>
                        <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.user }}</a></td>
                            <td><a class="navi-link" href="/tickets/id/{{ ticket.id }}">{{ ticket.title }}</a></td>
                            <td>{{ ticket.created }}</td>
                            {% if ticket.blocked == True %}
                                <td><span class="badge badge-danger m-0">Blocked</span></td>
                            {% elif ticket.solved == True %}
                                <td><span class="badge badge-warning m-0">Closed</span></td>
                                {% else %}
                                <td><span class="badge badge-primary m-0">Open</span></td>
                            {% endif %}
                            <td><span>{{ ticket.handled_by }}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            </div>
        </div>
    </div>
</div>
    </main>
    <!--Main layout-->

  <!-- Full Page Intro -->

{% endblock %}

tickets/templates/tickets/user_sidebar.html
                <div class="author-card pb-3">
                    <div class="author-card-cover" style="background-image: url('https://i.imgur.com/OUgq5HJ.png');"></div>
                    <div class="author-card-profile">
                        <div class="author-card-avatar"><img src="https://mc-heads.net/head/{{ user.nickname }}" alt="{{ user.username }}">
                        </div>
                        <div class="author-card-details">
                            <h5 class="author-card-name text-lg">{% if user.is_superuser %}<p class="badge badge-danger">Admin</p> {% endif %} {{ user.nickname }}</h5><span class="author-card-position">Joined {{ user.date_joined|date:"d M Y" }}</span>
                        </div>
                    </div>
                </div>