Main/urls.py
from django.urls import path
from .views import home, logout, login_view, register_view, security

app_name = 'Main'

urlpatterns = [
    path('', home, name='Home'),
    path('login/', login_view, name='Login'),
    path('register/', register_view, name='Register'),
    path('logout/', logout, name='logout'),
    path('security/', security, name='security')
]

Main/forms.py
from django import forms
from .models import User
from django.core.validators import validate_email, validate_slug
from django.contrib.auth.password_validation import validate_password


class SecurityValidate(forms.Form):
    email_new = forms.CharField(required=False)
    password_new = forms.CharField(required=False)
    password = forms.CharField(error_messages={'required': 'Password can not be empty'})

    def clean(self):
        email_new = str(self.cleaned_data.get('email_new'))
        password_new = str(self.cleaned_data.get('password_new'))
        password = str(self.cleaned_data.get('password'))
        if password is None:
            raise forms.ValidationError('Password can not be empty')
        if password_new is None and email_new is None:
            raise forms.ValidationError('You do not changing anything')
        if email_new is not None and email_new is not '':
            try:
                validate_email(email_new)
            except forms.ValidationError:
                raise forms.ValidationError("Email is not correct")
        if password_new is not None and password_new is not '':
            try:
                validate_password(password_new, self)
            except forms.ValidationError as error:
                raise forms.ValidationError(error)
        return True


class LoginValidate(forms.Form):
    username = forms.CharField(error_messages={'required': 'Username can not be empty'})
    password = forms.CharField(error_messages={'required': 'Password can not be empty'})

    def clean(self):
        username = str(self.cleaned_data.get('username'))
        password = str(self.cleaned_data.get('password'))
        if username is None or password is None:
            raise forms.ValidationError('Username or Password can not be empty')
        if User.objects.filter(username=username).count() != 0:
            user = User.objects.filter(username=username).first()
            if user.check_password(password):
                return True
            else:
                raise forms.ValidationError('Username or Password are not valid')
        else:
            raise forms.ValidationError('Username or Password are not valid1')


class RegisterValidate(forms.Form):
    username = forms.CharField(error_messages={'required': 'Username can not be empty'})
    nickname = forms.CharField(error_messages={'required': 'Nickname can not be empty'})
    email = forms.CharField(error_messages={'required': 'Email address can not be empty'})
    password = forms.CharField(error_messages={'required': 'Password can not be empty'})
    password2 = forms.CharField(error_messages={'required': 'Please retype the password'})
    tos = forms.BooleanField(required=False)

    def clean(self):
        username = str(self.cleaned_data.get('username'))
        nickname = str(self.cleaned_data.get('nickname'))
        email = str(self.cleaned_data.get('email'))
        password = str(self.cleaned_data.get('password'))
        password2 = str(self.cleaned_data.get('password2'))
        tos = self.cleaned_data.get('tos')
        try:
            validate_email(email)
        except forms.ValidationError:
            raise forms.ValidationError("Email is not correct")
        try:
            validate_slug(username)
        except forms.ValidationError:
            raise forms.ValidationError("Username is not correct")
        try:
            validate_slug(nickname)
        except forms.ValidationError:
            raise forms.ValidationError("Nickname is not correct")
        try:
            validate_password(password, self)
        except forms.ValidationError as error:
            raise forms.ValidationError(error)
        if password != password2:
            raise forms.ValidationError('Passwords are not identical')
        if tos is False:
            raise forms.ValidationError('ToS need to be accepted')
        if User.objects.filter(username=username).count() != 0:
            raise forms.ValidationError('Username already exists')
        if User.objects.filter(nickname=nickname).count() != 0:
            raise forms.ValidationError('Nickname already exists')
        if User.objects.filter(email=email).count() != 0:
            raise forms.ValidationError('Email is already claimed')
        return True

Main/templates/Main/data_modal.html
<!-- Modal -->
<div class="modal fade" id="show_data" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for u in user_sec  %}
            <h5><strong><i class="fas fa-user ml-2"></i> Username: {{ u.username }}</strong><br></h5>
            <h5><strong><i class="fas fa-user-ninja ml-2"></i> Nickname: {{ u.nickname }}</strong><br></h5>
            <h5><strong><i class="fas fa-envelope-open ml-2"></i> Email address: {{ u.email }}</strong><br></h5>
            <h5><strong><i class="fas fa-history ml-2"></i> Last login: {{ u.last_login }}</strong><br></h5>
            <h5><strong><i class="fas fa-handshake ml-2"></i> Join date: {{ u.date_joined }}</strong><br></h5>
        {% endfor %}
        
      </div>
    </div>
  </div>
</div>

Main/templates/Main/index.html
{% extends 'Main/templates/root.html' %}
{% block content %}

    <!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Lorem ipsum</h1>

            <hr class="hr-light">

            <p>
              <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Duis ut nisi tempus velit sollicitudin fermentum sed id quam. Nam eu sem vitae leo pretium iaculis et eget tortor. Sed molestie lorem id dolor euismod porta.</strong>
            </p>

            <a target="_blank" href="" class="btn btn-indigo btn-lg">Check for more
              <i class="fas fa-graduation-cap ml-2"></i>
            </a>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
    <!--Main layout-->
    <main>
      <div class="container">

        {% include 'Main/post.html' %}

      </div>
    </main>
    <!--Main layout-->

  <!-- Full Page Intro -->

{% endblock %}

Main/templates/Main/login.html
{% extends 'Main/templates/root.html' %}
{% block content %}
<!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Lorem ipsum</h1>

            <hr class="hr-light">

            <p>
              <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Duis ut nisi tempus velit sollicitudin fermentum sed id quam. Nam eu sem vitae leo pretium iaculis et eget tortor. Sed molestie lorem id dolor euismod porta.</strong>
            </p>

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 col-xl-5 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">
            {% for error in errors %}
                <p class="badge badge-danger">{{ error|striptags }}</p>
            {% endfor %}
                <!-- Form -->
                <form method="post"> {% csrf_token %}
                  <h1 class="h3 mb-3 font-weight-normal">Please log in</h1>
                  <label for="username" class="sr-only">Username</label>
                  <input type="text" id="id_username" class="form-control" name="username" placeholder="Your username" required autofocus><br/>
                  <label for="password" class="sr-only">Password</label>
                  <input type="password" id="id_password" class="form-control" name="password" placeholder="Your password" required><br/>
                  <div class="checkbox mb-3">
                    <label>
                      <input type="checkbox" value="Yes" name="remember_me"> Remember me
                    </label>
                  </div>
                  <input class="btn btn-lg btn-primary btn-block" type="submit" value="Sign in" />
                </form>
                <!-- Form -->

              </div>

            </div>
            <!--/.Card-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
  <!-- Full Page Intro -->
{% endblock %}

Main/templates/Main/post.html
{% for post in post_list %}
    <!--Section: Main info-->
        <section class="mt-5 wow fadeIn">

          <!--Grid row-->
          <div class="row">

            <!--Grid column-->
            <div class="col-md-6 mb-4">

              <img src="{{ post.image }}" class="img-fluid z-depth-1-half" alt="Image">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

              <!-- Main heading -->
              <h3 class="h3 mb-3">{{ post.title }}</h3>
                {{ post.text|safe }}
                <p class="blog-post-meta"><span class="badge badge-danger">{{ post.date }}</span> <span class="badge badge-info">{{ post.author }}</span></p>

            </div>
            <!--Grid column-->

          </div>
          <!--Grid row-->

        </section>
        <!--Section: Main info-->
{% endfor %}

Main/templates/Main/register.html
{% extends 'Main/templates/root.html' %}
{% block content %}
<!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Lorem ipsum</h1>

            <hr class="hr-light">

            <p>
              <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Duis ut nisi tempus velit sollicitudin fermentum sed id quam. Nam eu sem vitae leo pretium iaculis et eget tortor. Sed molestie lorem id dolor euismod porta.</strong>
            </p>

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 col-xl-5 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">
            {% for error in errors %}
                <p class="badge badge-danger">{{ error|striptags }}</p>
            {% endfor %}
                <!-- Form -->
                <form method="post"> {% csrf_token %}
                  <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
                  <label for="username" class="sr-only">Username</label>
                  <input type="text" id="id_username" class="form-control" name="username" placeholder="Your username" required autofocus><br/>
                  <label for="email" class="sr-only">Email address</label>
                  <input type="email" id="id_email" class="form-control" name="email" placeholder="Your email address" required autofocus><br/>
                  <label for="nickname" class="sr-only">Nickname</label>
                  <input type="text" id="id_nickname" class="form-control" name="nickname" placeholder="Your nick in game" required autofocus><br/>
                  <label for="password" class="sr-only">Password</label>
                  <input type="password" id="id_password" class="form-control" name="password" placeholder="Your password" required><br/>
                    <label for="password2" class="sr-only">Repeat password</label>
                  <input type="password" id="id_password2" class="form-control" name="password2" placeholder="Repeat password" required><br/>
                  <div class="checkbox mb-3">
                    <label>
                      <input type="checkbox" name="tos" required> I accept ToS
                    </label>
                  </div>
                  <input class="btn btn-lg btn-primary btn-block" type="submit" value="Sign up" />
                </form>
                <!-- Form -->

              </div>

            </div>
            <!--/.Card-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
  <!-- Full Page Intro -->
{% endblock %}

Main/templates/Main/security.html
{% extends 'Main/templates/root.html' %}
{% block content %}
    {% include 'Main/data_modal.html' %}
<!-- Full Page Intro -->
  <div class="view full-page-intro" style="background-image: url('https://i.imgur.com/OUgq5HJ.png'); background-repeat: no-repeat; background-size: cover;">

    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

      <!-- Content -->
      <div class="container">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4 white-text text-center text-md-left">

            <h1 class="display-4 font-weight-bold">Security</h1>

            <hr class="hr-light">

            <p>
              <strong>If you don't want to change something just leave this filed empty</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Duis ut nisi tempus velit sollicitudin fermentum sed id quam. Nam eu sem vitae leo pretium iaculis et eget tortor. Sed molestie lorem id dolor euismod porta.</strong>
            </p>
            <a target="_blank" data-toggle="modal" data-target="#show_data" class="btn btn-indigo btn-lg">Show your data
              <i class="fas fa-key ml-2"></i>
            </a>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 col-xl-5 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">
            {% for error in errors %}
                <p class="badge badge-danger">{{ error|striptags }}</p>
            {% endfor %}
                <!-- Form -->
                <form method="post"> {% csrf_token %}
                  <h1 class="h3 mb-3 font-weight-normal">Change your data</h1>
                  <label for="email_new" class="sr-only">New E-mail address</label>
                  <input type="email" id="id_email_new" class="form-control" name="email_new" placeholder="New email" autofocus><br/>
                  <label for="password_new" class="sr-only">New password</label>
                  <input type="password" id="id_password_new" class="form-control" name="password_new" placeholder="New password" autofocus><br/>
                  <label for="password" class="sr-only">Password</label>
                  <input type="password" id="id_password" class="form-control" name="password" placeholder="Your actual password" required><br/>
                  <input class="btn btn-lg btn-primary btn-block" type="submit" value="Change" />
                </form>
                <!-- Form -->

              </div>

            </div>
            <!--/.Card-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
      <!-- Content -->

    </div>
    <!-- Mask & flexbox options-->

  </div>
  <!-- Full Page Intro -->
{% endblock %}